In [1]:
import numpy as np
import pandas as pd

In [2]:
movies=pd.read_csv("movies.csv")
ratings=pd.read_csv("ratings.csv")
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [3]:
new_df=pd.merge(ratings,movies,on='movieId').drop(['timestamp'],axis=1)
movies.shape

(9742, 3)

In [4]:
new_df.head(20)

userId  movieId  rating             title  \
0        1        1     4.0  Toy Story (1995)   
1        5        1     4.0  Toy Story (1995)   
2        7        1     4.5  Toy Story (1995)   
3       15        1     2.5  Toy Story (1995)   
4       17        1     4.5  Toy Story (1995)   
5       18        1     3.5  Toy Story (1995)   
6       19        1     4.0  Toy Story (1995)   
7       21        1     3.5  Toy Story (1995)   
8       27        1     3.0  Toy Story (1995)   
9       31        1     5.0  Toy Story (1995)   
10      32        1     3.0  Toy Story (1995)   
11      33        1     3.0  Toy Story (1995)   
12      40        1     5.0  Toy Story (1995)   
13      43        1     5.0  Toy Story (1995)   
14      44        1     3.0  Toy Story (1995)   
15      45        1     4.0  Toy Story (1995)   
16      46        1     5.0  Toy Story (1995)   
17      50        1     3.0  Toy Story (1995)   
18      54        1     3.0  Toy Story (1995)   
19      57        1     5.0  Toy Story (1995)   

                                         genres  
0   Adventure|Animation|Children|Comedy|Fantasy  
1   Adventure|Animation|Children|Comedy|Fantasy  
2   Adventure|Animation|Children|Comedy|Fantasy  
3   Adventure|Animation|Children|Comedy|Fantasy  
4   Adventure|Animation|Children|Comedy|Fantasy  
5   Adventure|Animation|Children|Comedy|Fantasy  
6   Adventure|Animation|Children|Comedy|Fantasy  
7   Adventure|Animation|Children|Comedy|Fantasy  
8   Adventure|Animation|Children|Comedy|Fantasy  
9   Adventure|Animation|Children|Comedy|Fantasy  
10  Adventure|Animation|Children|Comedy|Fantasy  
11  Adventure|Animation|Children|Comedy|Fantasy  
12  Adventure|Animation|Children|Comedy|Fantasy  
13  Adventure|Animation|Children|Comedy|Fantasy  
14  Adventure|Animation|Children|Comedy|Fantasy  
15  Adventure|Animation|Children|Comedy|Fantasy  
16  Adventure|Animation|Children|Comedy|Fantasy  
17  Adventure|Animation|Children|Comedy|Fantasy  
18  Adventure|Animation|Children|Comedy|Fantasy  
19  Adventure|Animation|Children|Comedy|Fantasy

In [5]:
new_df.shape

(100836, 5)

In [6]:
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [7]:
v = new_df.userId.value_counts()
v_df=new_df[new_df.userId.isin(v.index[v.gt(10)])]
v

414    2698
599    2478
474    2108
448    1864
274    1346
       ... 
431      20
194      20
257      20
207      20
189      20
Name: userId, Length: 610, dtype: int64

In [8]:
v_df.shape

(100836, 5)

In [9]:
v_df.userId.value_counts()

414    2698
599    2478
474    2108
448    1864
274    1346
       ... 
431      20
194      20
257      20
207      20
189      20
Name: userId, Length: 610, dtype: int64

In [10]:
## for userId 194
## taking his top three movies on the basis of his ratings

In [11]:
df=v_df.loc[new_df['userId']==431]
sdf=df.sort_values('rating',ascending=False)
sdf.head(20)
    

userId  movieId  rating                                 title  \
51570     431      555     5.0                   True Romance (1993)   
70028     431     1233     4.5          Boot, Das (Boat, The) (1981)   
8989      431     1278     4.0             Young Frankenstein (1974)   
10056     431     1625     4.0                      Game, The (1997)   
50737     431     1234     4.0                     Sting, The (1973)   
3819      431      543     3.5   So I Married an Axe Murderer (1993)   
64910     431     3948     3.0               Meet the Parents (2000)   
58482     431      903     3.0                        Vertigo (1958)   
1193      431      163     3.0                      Desperado (1995)   
12216     431     2406     3.0            Romancing the Stone (1984)   
32390     431      485     2.5               Last Action Hero (1993)   
59195     431     1376     2.5  Star Trek IV: The Voyage Home (1986)   
3868      431      552     2.5          Three Musketeers, The (1993)   
32288     431      466     2.0           Hot Shots! Part Deux (1993)   
45341     431      172     2.0                Johnny Mnemonic (1995)   
44650     431     1639     1.5                    Chasing Amy (1997)   
64537     431     2006     1.5             Mask of Zorro, The (1998)   
33418     431      802     1.5                     Phenomenon (1996)   
28800     431      158     1.0                         Casper (1995)   
31981     431      435     0.5                      Coneheads (1993)   

                                genres  
51570                   Crime|Thriller  
70028                 Action|Drama|War  
8989                    Comedy|Fantasy  
10056           Drama|Mystery|Thriller  
50737                     Comedy|Crime  
3819           Comedy|Romance|Thriller  
64910                           Comedy  
58482   Drama|Mystery|Romance|Thriller  
1193            Action|Romance|Western  
12216  Action|Adventure|Comedy|Romance  
32390  Action|Adventure|Comedy|Fantasy  
59195          Adventure|Comedy|Sci-Fi  
3868   Action|Adventure|Comedy|Romance  
32288                Action|Comedy|War  
45341           Action|Sci-Fi|Thriller  
44650             Comedy|Drama|Romance  
64537            Action|Comedy|Romance  
33418                    Drama|Romance  
28800               Adventure|Children  
31981                    Comedy|Sci-Fi

In [12]:
x_df=sdf[0:5]
x_df.head()

userId  movieId  rating                         title  \
51570     431      555     5.0           True Romance (1993)   
70028     431     1233     4.5  Boot, Das (Boat, The) (1981)   
8989      431     1278     4.0     Young Frankenstein (1974)   
10056     431     1625     4.0              Game, The (1997)   
50737     431     1234     4.0             Sting, The (1973)   

                       genres  
51570          Crime|Thriller  
70028        Action|Drama|War  
8989           Comedy|Fantasy  
10056  Drama|Mystery|Thriller  
50737            Comedy|Crime

In [13]:
z_df=pd.concat([sdf,x_df,x_df]).drop_duplicates(keep=False)
z_df.drop(['userId','rating'],axis=1,inplace=True)


In [14]:
movies_df=pd.concat([movies,z_df,z_df]).drop_duplicates(keep=False)

In [15]:
movies_df.shape

(9727, 3)

In [16]:
movies_df['genres']=movies_df['genres'].str.replace('|',' ')   

C:\Users\agraw\AppData\Local\Temp/ipykernel_2808/1162253944.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  movies_df['genres']=movies_df['genres'].str.replace('|',' ')


In [17]:
movies_df['genres']=movies_df['genres'].apply(lambda x:x.lower())
movies_df = movies_df[~movies_df.genres.str.contains("no genres listed", na=False)]
movies_df['genres']=movies_df['genres'].str.replace('-',' ')
movies_df.shape

(9693, 3)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [19]:
vectors=cv.fit_transform(movies['genres']).toarray()
from sklearn.metrics.pairwise import cosine_similarity

In [34]:
vectors

array([[0, 1, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
similarity=cosine_similarity(vectors)
similarity

array([[1.        , 0.77459667, 0.31622777, ..., 0.        , 0.31622777,
        0.4472136 ],
       [0.77459667, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.31622777, 0.        , 1.        , ..., 0.        , 0.        ,
        0.70710678],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.31622777, 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.4472136 , 0.        , 0.70710678, ..., 0.        , 0.        ,
        1.        ]])

In [22]:
def recommend(movie):
    movie_index=movies[movies['title']==movie].index[0]
    distances=similarity[movie_index]
    movie_list=sorted(list(enumerate(distances)),reverse=True, key =lambda x:x[1])[0:4]
    for i in movie_list:
        print(movies.iloc[i[0]].title,movies.iloc[i[0]].genres,i[1])
        
    return

In [23]:
for i in x_df['title']:
    recommend(i)

Romeo Is Bleeding (1993) Crime|Thriller 0.9999999999999998
True Romance (1993) Crime|Thriller 0.9999999999999998
Escort, The (Scorta, La) (1993) Crime|Thriller 0.9999999999999998
Heaven's Prisoners (1996) Crime|Thriller 0.9999999999999998
Braveheart (1995) Action|Drama|War 1.0000000000000002
Apocalypse Now (1979) Action|Drama|War 1.0000000000000002
Boot, Das (Boat, The) (1981) Action|Drama|War 1.0000000000000002
All Quiet on the Western Front (1930) Action|Drama|War 1.0000000000000002
Reckless (1995) Comedy|Fantasy 0.9999999999999998
Drop Dead Fred (1991) Comedy|Fantasy 0.9999999999999998
Young Frankenstein (1974) Comedy|Fantasy 0.9999999999999998
Devil and Max Devlin, The (1981) Comedy|Fantasy 0.9999999999999998
Client, The (1994) Drama|Mystery|Thriller 1.0000000000000002
39 Steps, The (1935) Drama|Mystery|Thriller 1.0000000000000002
Game, The (1997) Drama|Mystery|Thriller 1.0000000000000002
The Devil's Advocate (1997) Drama|Mystery|Thriller 1.0000000000000002
Don't Be a Menace to Sou

In [24]:
movie_index=movies[movies['title']=='True Romance (1993)'].index[0]
movie_index

486

In [25]:
movies.iloc[486].title

'True Romance (1993)'

In [26]:
distances=similarity[486]
distances

array([0., 0., 0., ..., 0., 0., 0.])

In [27]:
movie_lists=sorted(list(enumerate(distances)),reverse=True, key =lambda x:x[1])[0:4]
movie_lists

[(456, 0.9999999999999998),
 (486, 0.9999999999999998),
 (499, 0.9999999999999998),
 (591, 0.9999999999999998)]

In [28]:
for i in movie_lists:
    print(movies.iloc[i[0]].title)

Romeo Is Bleeding (1993)
True Romance (1993)
Escort, The (Scorta, La) (1993)
Heaven's Prisoners (1996)


In [29]:
recommend('True Romance (1993)')

Romeo Is Bleeding (1993) Crime|Thriller 0.9999999999999998
True Romance (1993) Crime|Thriller 0.9999999999999998
Escort, The (Scorta, La) (1993) Crime|Thriller 0.9999999999999998
Heaven's Prisoners (1996) Crime|Thriller 0.9999999999999998


In [30]:
movie_index=movies[movies['genres']=='Adventure|Animation|Children|Comedy|Fantasy']

In [31]:
movie_index


movieId                                              title  \
0           1                                   Toy Story (1995)   
1706     2294                                        Antz (1998)   
2355     3114                                 Toy Story 2 (1999)   
2809     3754     Adventures of Rocky and Bullwinkle, The (2000)   
3000     4016                   Emperor's New Groove, The (2000)   
3568     4886                              Monsters, Inc. (2001)   
6194    45074                                   Wild, The (2006)   
6486    53121                             Shrek the Third (2007)   
6948    65577                     Tale of Despereaux, The (2008)   
7760    91355  Asterix and the Vikings (Astérix et les Viking...   
8219   103755                                       Turbo (2013)   
8927   136016                           The Good Dinosaur (2015)   
9430   166461                                       Moana (2016)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1706  Adventure|Animation|Children|Comedy|Fantasy  
2355  Adventure|Animation|Children|Comedy|Fantasy  
2809  Adventure|Animation|Children|Comedy|Fantasy  
3000  Adventure|Animation|Children|Comedy|Fantasy  
3568  Adventure|Animation|Children|Comedy|Fantasy  
6194  Adventure|Animation|Children|Comedy|Fantasy  
6486  Adventure|Animation|Children|Comedy|Fantasy  
6948  Adventure|Animation|Children|Comedy|Fantasy  
7760  Adventure|Animation|Children|Comedy|Fantasy  
8219  Adventure|Animation|Children|Comedy|Fantasy  
8927  Adventure|Animation|Children|Comedy|Fantasy  
9430  Adventure|Animation|Children|Comedy|Fantasy